# .air.toml
[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./tmp/main ."
# Binary file yields from `cmd`.
bin = "tmp/main"
# Customize binary.
full_bin = "APP_ENV=development APP_USER=air ./tmp/main"

# These are the default values
[watch]
# Directories to watch
includes = ["."]
# Excluding these files or directories
excludes = ["tmp", "*repos*"]
# Watching these filename suffixes
suffixes = [".go"]

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color is found, use the default color
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete binary after Air ends
clean = true
