# Start from the base golang image
FROM golang:1.22.0

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy everything from the current directory to the PWD(Present Working Directory) inside the container
COPY . .

RUN git config --global --add safe.directory '*'

RUN git config --system --add safe.directory '*'

RUN go install github.com/cosmtrek/air@latest

# Set the Current Working Directory inside the container to reposync directory
WORKDIR /app/server

# Download all the dependencies
RUN go mod download

RUN chmod 777 ./tmp

# This command starts our application using air's live reload
CMD ["air"]