FROM golang:1.22.0

WORKDIR /app

COPY . .

RUN git config --global pull.rebase false

RUN git config --global --add safe.directory '*'

RUN git config --system --add safe.directory '*'

# adds default user for git
RUN git config --global user.email info@openq.dev
RUN git config --global user.name "OpenQ Default"

WORKDIR /app/reposync

RUN go mod download

RUN go build -o main .

CMD ["./main"]
