FROM golang:1.21.6

WORKDIR /app

COPY . .

RUN git config --global pull.rebase false

RUN git config --global --add safe.directory '*'

WORKDIR /app/reposync

RUN go mod download

RUN go build -o main .

CMD ["./main"]
