const fs = require('fs');
const crypto = require('crypto');

// Function to generate a random 7 digit number
function generateRandomId() {
    return Math.floor(1000000 + Math.random() * 9000000);
}

// Read the emails from the text file
const emails = fs.readFileSync('nixos_emails.txt', 'utf-8').split('\n').filter(Boolean);

// Start of the SQL file
let sqlFileContent = '-- SQL file generated by Node.js script\n\n';

// Loop through the emails and generate the SQL insert statements
for (let email of emails) {
    const restId = generateRandomId();
    sqlFileContent += `INSERT INTO github_user_rest_id_author_emails (rest_id, email) VALUES (${restId}, '${email}');\n`;
}

// Write the SQL file
fs.writeFileSync('insert_emails.sql', sqlFileContent);