// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: dependencies.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const bulkInsertDependencies = `-- name: BulkInsertDependencies :many

INSERT INTO dependencies (
    dependency_name,
    dependency_file
) VALUES (
    $1, unnest($2::varchar[])
)
ON CONFLICT (dependency_name, dependency_file) DO UPDATE SET dependency_name = excluded.dependency_name
RETURNING internal_id
`

type BulkInsertDependenciesParams struct {
	DependencyName string   `json:"dependency_name"`
	Column2        []string `json:"column_2"`
}

func (q *Queries) BulkInsertDependencies(ctx context.Context, arg BulkInsertDependenciesParams) ([]int32, error) {
	rows, err := q.query(ctx, q.bulkInsertDependenciesStmt, bulkInsertDependencies, arg.DependencyName, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var internal_id int32
		if err := rows.Scan(&internal_id); err != nil {
			return nil, err
		}
		items = append(items, internal_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUnusedDependencies = `-- name: DeleteUnusedDependencies :exec
DELETE FROM dependencies WHERE dependency_file LIKE $1 AND dependency_file != $2
`

type DeleteUnusedDependenciesParams struct {
	DependencyFileLike string `json:"dependency_file_like"`
	DependencyFile     string `json:"dependency_file"`
}

func (q *Queries) DeleteUnusedDependencies(ctx context.Context, arg DeleteUnusedDependenciesParams) error {
	_, err := q.exec(ctx, q.deleteUnusedDependenciesStmt, deleteUnusedDependencies, arg.DependencyFileLike, arg.DependencyFile)
	return err
}

const getDependencies = `-- name: GetDependencies :many
SELECT d.dependency_name,
d.dependency_file,
d.internal_id,
rd.updated_at
 FROM repos_to_dependencies rd
LEFT JOIN dependencies d ON rd.dependency_id = d.internal_id
WHERE rd.url = $1
`

type GetDependenciesRow struct {
	DependencyName sql.NullString `json:"dependency_name"`
	DependencyFile sql.NullString `json:"dependency_file"`
	InternalID     sql.NullInt32  `json:"internal_id"`
	UpdatedAt      sql.NullInt64  `json:"updated_at"`
}

func (q *Queries) GetDependencies(ctx context.Context, url string) ([]GetDependenciesRow, error) {
	rows, err := q.query(ctx, q.getDependenciesStmt, getDependencies, url)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDependenciesRow
	for rows.Next() {
		var i GetDependenciesRow
		if err := rows.Scan(
			&i.DependencyName,
			&i.DependencyFile,
			&i.InternalID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDependenciesByFiles = `-- name: GetDependenciesByFiles :many

SELECT dependency_name
FROM dependencies
WHERE dependency_file LIKE $1
  AND dependency_file != $2
GROUP BY dependency_name
`

type GetDependenciesByFilesParams struct {
	DependencyFileLike string `json:"dependency_file_like"`
	DependencyFile     string `json:"dependency_file"`
}

func (q *Queries) GetDependenciesByFiles(ctx context.Context, arg GetDependenciesByFilesParams) ([]string, error) {
	rows, err := q.query(ctx, q.getDependenciesByFilesStmt, getDependenciesByFiles, arg.DependencyFileLike, arg.DependencyFile)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var dependency_name string
		if err := rows.Scan(&dependency_name); err != nil {
			return nil, err
		}
		items = append(items, dependency_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDependenciesByNames = `-- name: GetDependenciesByNames :many
SELECT internal_id, dependency_name, dependency_file FROM dependencies WHERE dependency_name =ANY($1::text[])
`

func (q *Queries) GetDependenciesByNames(ctx context.Context, dollar_1 []string) ([]Dependency, error) {
	rows, err := q.query(ctx, q.getDependenciesByNamesStmt, getDependenciesByNames, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dependency
	for rows.Next() {
		var i Dependency
		if err := rows.Scan(&i.InternalID, &i.DependencyName, &i.DependencyFile); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDependency = `-- name: GetDependency :one
SELECT internal_id, dependency_name, dependency_file FROM dependencies WHERE dependency_name = $1 AND dependency_file = $2
`

type GetDependencyParams struct {
	DependencyName string `json:"dependency_name"`
	DependencyFile string `json:"dependency_file"`
}

func (q *Queries) GetDependency(ctx context.Context, arg GetDependencyParams) (Dependency, error) {
	row := q.queryRow(ctx, q.getDependencyStmt, getDependency, arg.DependencyName, arg.DependencyFile)
	var i Dependency
	err := row.Scan(&i.InternalID, &i.DependencyName, &i.DependencyFile)
	return i, err
}

const upsertMissingDependencies = `-- name: UpsertMissingDependencies :exec

INSERT INTO dependencies (
    dependency_name,
    dependency_file
) VALUES (
    unnest($2::text[]), $1
)
ON CONFLICT DO NOTHING
RETURNING internal_id
`

type UpsertMissingDependenciesParams struct {
	DependencyFile  string   `json:"dependency_file"`
	DependencyNames []string `json:"dependency_names"`
}

func (q *Queries) UpsertMissingDependencies(ctx context.Context, arg UpsertMissingDependenciesParams) error {
	_, err := q.exec(ctx, q.upsertMissingDependenciesStmt, upsertMissingDependencies, arg.DependencyFile, pq.Array(arg.DependencyNames))
	return err
}
