// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: dependencies_to_repos.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const bulkInsertRepoDependencyInfo = `-- name: BulkInsertRepoDependencyInfo :exec
INSERT INTO dependencies_to_repos (github_repo_internal_id, dependency_name, first_commit_date, date_added, date_removed) VALUES (  
	unnest($1::int[]),  
	unnest($2::varchar[]),
	unnest($3::bigint[]),
	unnest($4::bigint[]),
	unnest($5::bigint[])
)
ON CONFLICT (dependency_name) DO NOTHING
RETURNING internal_id, github_repo_internal_id, dependency_name, first_commit_date, date_added, date_removed
`

type BulkInsertRepoDependencyInfoParams struct {
	Column1 []int32  `json:"column_1"`
	Column2 []string `json:"column_2"`
	Column3 []int64  `json:"column_3"`
	Column4 []int64  `json:"column_4"`
	Column5 []int64  `json:"column_5"`
}

func (q *Queries) BulkInsertRepoDependencyInfo(ctx context.Context, arg BulkInsertRepoDependencyInfoParams) error {
	_, err := q.exec(ctx, q.bulkInsertRepoDependencyInfoStmt, bulkInsertRepoDependencyInfo,
		pq.Array(arg.Column1),
		pq.Array(arg.Column2),
		pq.Array(arg.Column3),
		pq.Array(arg.Column4),
		pq.Array(arg.Column5),
	)
	return err
}

const queryBulkRepoDependencyInfo = `-- name: QueryBulkRepoDependencyInfo :many
SELECT internal_id, github_repo_internal_id, dependency_name, first_commit_date, date_added, date_removed FROM dependencies_to_repos WHERE github_repo_internal_id = ANY($1::int[]) AND dependency_name = $2
`

type QueryBulkRepoDependencyInfoParams struct {
	Column1        []int32        `json:"column_1"`
	DependencyName sql.NullString `json:"dependency_name"`
}

func (q *Queries) QueryBulkRepoDependencyInfo(ctx context.Context, arg QueryBulkRepoDependencyInfoParams) ([]DependenciesToRepo, error) {
	rows, err := q.query(ctx, q.queryBulkRepoDependencyInfoStmt, queryBulkRepoDependencyInfo, pq.Array(arg.Column1), arg.DependencyName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DependenciesToRepo
	for rows.Next() {
		var i DependenciesToRepo
		if err := rows.Scan(
			&i.InternalID,
			&i.GithubRepoInternalID,
			&i.DependencyName,
			&i.FirstCommitDate,
			&i.DateAdded,
			&i.DateRemoved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
