// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: repo_latest_commits.sql

package database

import (
	"context"
)

const getRepoLatestCommit = `-- name: GetRepoLatestCommit :one
SELECT repo_name, last_push_event_time FROM repo_latest_commit WHERE repo_name = $1
`

func (q *Queries) GetRepoLatestCommit(ctx context.Context, repoName string) (RepoLatestCommit, error) {
	row := q.queryRow(ctx, q.getRepoLatestCommitStmt, getRepoLatestCommit, repoName)
	var i RepoLatestCommit
	err := row.Scan(&i.RepoName, &i.LastPushEventTime)
	return i, err
}
