name: Build UserSync Image

on:
  workflow_call:
    inputs:
      version:
        description: "The version to tag the usersync image - e.g. 1.2.32"
        required: true
        type: string
      environment:
        description: "The environment to deploy usersync - e.g. development, staging, production"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.usersync
          push: true
          tags: openq/gitguru-users:${{ inputs.environment }}-${{ inputs.version }}

  tagHelm:
    needs: build
    uses: OpenQDev/OpenQ-Workflows/.github/workflows/tag.yml@main
    with:
      APP: gitguru_users
      VERSION: ${{ inputs.environment }}-${{ inputs.version }}
      ENVIRONMENT: ${{ inputs.environment }}
    secrets:
      PAT: ${{ secrets.PAT }}